### ISSUE TITLE
1.35.8 version sends a lot of errors to the console

### ISSUE THREAD

**Issue by CloudM1nd3** [K0bus/CreativeManager#35]
version 1.35.8 , plugin is working correctly but there is error in console every second

[23:01:52 ERROR]: Could not pass event InventoryCreativeEvent to CreativeManager v1.35.8
java.lang.NoClassDefFoundError: Could not initialize class fr.k0bus.creativemanager_libs.tr7zw.lib.nbtapi.utils.nmsmappings.ReflectionMethod
        at CreativeManager-1.35.8 (2).jar/fr.k0bus.creativemanager_libs.tr7zw.lib.nbtapi.NBTItem.getCompound(NBTItem.java:113) ~[CreativeManager-1.35.8 (2).jar:?]
        at CreativeManager-1.35.8 (2).jar/fr.k0bus.creativemanager_libs.tr7zw.lib.nbtapi.NBTItem.hasNBTData(NBTItem.java:263) ~[CreativeManager-1.35.8 (2).jar:?]
        at CreativeManager-1.35.8 (2).jar/fr.k0bus.creativemanager.event.InventoryMove.checkNBT(InventoryMove.java:101) ~[CreativeManager-1.35.8 (2).jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor519.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-9-d75961f]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[pufferfish-1.21.1.jar:1.21.1-9-d75961f]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[pufferfish-1.21.1.jar:1.21.1-9-d75961f]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleSetCreativeModeSlot(ServerGamePacketListenerImpl.java:3329) ~[pufferfish-1.21.1.jar:1.21.1-9-d75961f]
        at net.minecraft.network.protocol.game.ServerboundSetCreativeModeSlotPacket.handle(ServerboundSetCreativeModeSlotPacket.java:30) ~[pufferfish-1.21.1.jar:1.21.1-9-d75961f]
        at net.minecraft.network.protocol.game.ServerboundSetCreativeModeSlotPacket.handle(ServerboundSetCreativeModeSlotPacket.java:20) ~[pufferfish-1.21.1.jar:1.21.1-9-d75961f]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[pufferfish-1.21.1.jar:1.21.1-9-d75961f]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[pufferfish-1.21.1.jar:1.21.1-9-d75961f]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[pufferfish-1.21.1.jar:1.21.1-9-d75961f]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[pufferfish-1.21.1.jar:1.21.1-9-d75961f]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1544) ~[pufferfish-1.21.1.jar:1.21.1-9-d75961f]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[pufferfish-1.21.1.jar:1.21.1-9-d75961f]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[pufferfish-1.21.1.jar:1.21.1-9-d75961f]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1521) ~[pufferfish-1.21.1.jar:1.21.1-9-d75961f]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1514) ~[pufferfish-1.21.1.jar:1.21.1-9-d75961f]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[pufferfish-1.21.1.jar:1.21.1-9-d75961f]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1473) ~[pufferfish-1.21.1.jar:1.21.1-9-d75961f]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1480) ~[pufferfish-1.21.1.jar:1.21.1-9-d75961f]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1325) ~[pufferfish-1.21.1.jar:1.21.1-9-d75961f]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:331) ~[pufferfish-1.21.1.jar:1.21.1-9-d75961f]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.ExceptionInInitializerError [in thread "Server thread"]
        at CreativeManager-1.35.8 (2).jar/fr.k0bus.creativemanager_libs.tr7zw.lib.nbtapi.utils.nmsmappings.ReflectionMethod.<clinit>(ReflectionMethod.java:24) ~[CreativeManager-1.35.8 (2).jar:?]
        ... 28 more

Java version 21
core version 1.21.1 pufferfish

What can i do to prevent this errror

**Comment by CloudM1nd3** [comment]
Among other things, there is a bug in which players, using any explosion, can break blocks in the region placed specifically in the creative. Neither worldguard nor anything else can save you from this. Because of this, we even had to turn off creeper explosions - after all, they can also cause a breakdown in the region.  In version 1.21, Wind Charge appeared - now players break blocks with them.

**Comment by CloudM1nd3** [comment]
The error indicated in the body of the report occurs when a person places an item in inventory slots from 9 to 27. In other cases there is no error
